# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(555, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_optimize = QtWidgets.QCheckBox(self.groupBox_2)
        self.check_optimize.setChecked(True)
        self.check_optimize.setObjectName("check_optimize")
        self.verticalLayout_2.addWidget(self.check_optimize)
        self.spin_timeOptimize = QtWidgets.QSpinBox(self.groupBox_2)
        self.spin_timeOptimize.setMaximum(999999)
        self.spin_timeOptimize.setProperty("value", 3)
        self.spin_timeOptimize.setObjectName("spin_timeOptimize")
        self.verticalLayout_2.addWidget(self.spin_timeOptimize)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.datetime_init = QtWidgets.QDateTimeEdit(self.frame)
        self.datetime_init.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 9, 1), QtCore.QTime(0, 0, 0)))
        self.datetime_init.setObjectName("datetime_init")
        self.horizontalLayout.addWidget(self.datetime_init)
        self.verticalLayout.addWidget(self.frame)
        self.frame1 = QtWidgets.QFrame(self.groupBox)
        self.frame1.setObjectName("frame1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.datetime_end = QtWidgets.QDateTimeEdit(self.frame1)
        self.datetime_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 9, 5), QtCore.QTime(0, 0, 0)))
        self.datetime_end.setObjectName("datetime_end")
        self.horizontalLayout_2.addWidget(self.datetime_end)
        self.verticalLayout.addWidget(self.frame1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.check_allPvs = QtWidgets.QRadioButton(self.groupBox_3)
        self.check_allPvs.setChecked(False)
        self.check_allPvs.setObjectName("check_allPvs")
        self.verticalLayout_3.addWidget(self.check_allPvs)
        self.check_opositeHLS = QtWidgets.QRadioButton(self.groupBox_3)
        self.check_opositeHLS.setObjectName("check_opositeHLS")
        self.verticalLayout_3.addWidget(self.check_opositeHLS)
        self.check_rfPv = QtWidgets.QRadioButton(self.groupBox_3)
        self.check_rfPv.setChecked(True)
        self.check_rfPv.setObjectName("check_rfPv")
        self.verticalLayout_3.addWidget(self.check_rfPv)
        self.check_earthtides = QtWidgets.QRadioButton(self.groupBox_3)
        self.check_earthtides.setObjectName("check_earthtides")
        self.verticalLayout_3.addWidget(self.check_earthtides)
        self.check_wellpressure = QtWidgets.QRadioButton(self.groupBox_3)
        self.check_wellpressure.setObjectName("check_wellpressure")
        self.verticalLayout_3.addWidget(self.check_wellpressure)
        self.check_selectPvs = QtWidgets.QRadioButton(self.groupBox_3)
        self.check_selectPvs.setObjectName("check_selectPvs")
        self.verticalLayout_3.addWidget(self.check_selectPvs)
        self.inputTxt_pvs = QtWidgets.QLineEdit(self.groupBox_3)
        self.inputTxt_pvs.setEnabled(False)
        self.inputTxt_pvs.setObjectName("inputTxt_pvs")
        self.verticalLayout_3.addWidget(self.inputTxt_pvs)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 2, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_dataLoaded = QtWidgets.QLabel(self.groupBox_4)
        self.label_dataLoaded.setMinimumSize(QtCore.QSize(0, 23))
        self.label_dataLoaded.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_dataLoaded.setStyleSheet("background-color: rgb(255, 99, 101);\n"
"color: rgb(0, 0, 0);\n"
"padding:3;")
        self.label_dataLoaded.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_dataLoaded.setObjectName("label_dataLoaded")
        self.verticalLayout_4.addWidget(self.label_dataLoaded)
        self.txt_loadedPvs = QtWidgets.QTextBrowser(self.groupBox_4)
        self.txt_loadedPvs.setMaximumSize(QtCore.QSize(16777215, 120))
        self.txt_loadedPvs.setObjectName("txt_loadedPvs")
        self.verticalLayout_4.addWidget(self.txt_loadedPvs)
        self.btn_fetchFromArchiver = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_fetchFromArchiver.setObjectName("btn_fetchFromArchiver")
        self.verticalLayout_4.addWidget(self.btn_fetchFromArchiver)
        self.btn_cleanData = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_cleanData.setObjectName("btn_cleanData")
        self.verticalLayout_4.addWidget(self.btn_cleanData)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setObjectName("log")
        self.gridLayout.addWidget(self.log, 2, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setContentsMargins(-1, 2, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame2 = QtWidgets.QFrame(self.groupBox_6)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_3.setContentsMargins(9, -1, 9, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.check_plotTime = QtWidgets.QRadioButton(self.frame2)
        self.check_plotTime.setObjectName("check_plotTime")
        self.horizontalLayout_3.addWidget(self.check_plotTime)
        self.check_plotFFT = QtWidgets.QRadioButton(self.frame2)
        self.check_plotFFT.setChecked(False)
        self.check_plotFFT.setObjectName("check_plotFFT")
        self.horizontalLayout_3.addWidget(self.check_plotFFT)
        self.check_plotCorrel = QtWidgets.QRadioButton(self.frame2)
        self.check_plotCorrel.setChecked(True)
        self.check_plotCorrel.setObjectName("check_plotCorrel")
        self.horizontalLayout_3.addWidget(self.check_plotCorrel)
        self.check_plotDirectional = QtWidgets.QRadioButton(self.frame2)
        self.check_plotDirectional.setObjectName("check_plotDirectional")
        self.horizontalLayout_3.addWidget(self.check_plotDirectional)
        self.verticalLayout_5.addWidget(self.frame2)
        self.frame2 = QtWidgets.QFrame(self.groupBox_6)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_4.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.check_plotStatic = QtWidgets.QRadioButton(self.frame2)
        self.check_plotStatic.setChecked(False)
        self.check_plotStatic.setObjectName("check_plotStatic")
        self.horizontalLayout_4.addWidget(self.check_plotStatic)
        self.check_plotDynamic = QtWidgets.QRadioButton(self.frame2)
        self.check_plotDynamic.setChecked(True)
        self.check_plotDynamic.setObjectName("check_plotDynamic")
        self.horizontalLayout_4.addWidget(self.check_plotDynamic)
        self.verticalLayout_5.addWidget(self.frame2)
        self.frame3 = QtWidgets.QFrame(self.groupBox_6)
        self.frame3.setObjectName("frame3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame3)
        self.horizontalLayout_5.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.check_plot2D = QtWidgets.QRadioButton(self.frame3)
        self.check_plot2D.setChecked(True)
        self.check_plot2D.setObjectName("check_plot2D")
        self.horizontalLayout_5.addWidget(self.check_plot2D)
        self.check_plot3D = QtWidgets.QRadioButton(self.frame3)
        self.check_plot3D.setObjectName("check_plot3D")
        self.horizontalLayout_5.addWidget(self.check_plot3D)
        self.verticalLayout_5.addWidget(self.frame3)
        self.line_3 = QtWidgets.QFrame(self.groupBox_6)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.frame_3 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_8.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.check_applyFilter = QtWidgets.QCheckBox(self.frame_3)
        self.check_applyFilter.setObjectName("check_applyFilter")
        self.horizontalLayout_8.addWidget(self.check_applyFilter)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.spin_filter_max = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.spin_filter_max.setObjectName("spin_filter_max")
        self.verticalLayout_6.addWidget(self.spin_filter_max)
        self.horizontalLayout_8.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.spin_filter_min = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.spin_filter_min.setObjectName("spin_filter_min")
        self.verticalLayout_8.addWidget(self.spin_filter_min)
        self.horizontalLayout_8.addWidget(self.frame_4)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.check_plotFiltSignal = QtWidgets.QCheckBox(self.groupBox_6)
        self.check_plotFiltSignal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check_plotFiltSignal.setTristate(False)
        self.check_plotFiltSignal.setObjectName("check_plotFiltSignal")
        self.verticalLayout_5.addWidget(self.check_plotFiltSignal)
        self.frame4 = QtWidgets.QFrame(self.groupBox_6)
        self.frame4.setObjectName("frame4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame4)
        self.horizontalLayout_6.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.check_saveFig = QtWidgets.QCheckBox(self.frame4)
        self.check_saveFig.setObjectName("check_saveFig")
        self.horizontalLayout_6.addWidget(self.check_saveFig)
        self.inputTxt_dirFig = QtWidgets.QLineEdit(self.frame4)
        self.inputTxt_dirFig.setInputMask("")
        self.inputTxt_dirFig.setText("")
        self.inputTxt_dirFig.setObjectName("inputTxt_dirFig")
        self.horizontalLayout_6.addWidget(self.inputTxt_dirFig)
        self.verticalLayout_5.addWidget(self.frame4)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.spin_chunck_day = QtWidgets.QSpinBox(self.frame_2)
        self.spin_chunck_day.setProperty("value", 1)
        self.spin_chunck_day.setObjectName("spin_chunck_day")
        self.horizontalLayout_7.addWidget(self.spin_chunck_day)
        self.spin_chunck_hour = QtWidgets.QSpinBox(self.frame_2)
        self.spin_chunck_hour.setObjectName("spin_chunck_hour")
        self.horizontalLayout_7.addWidget(self.spin_chunck_hour)
        self.spin_chunck_min = QtWidgets.QSpinBox(self.frame_2)
        self.spin_chunck_min.setObjectName("spin_chunck_min")
        self.horizontalLayout_7.addWidget(self.spin_chunck_min)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.btn_plot = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_plot.setEnabled(False)
        self.btn_plot.setObjectName("btn_plot")
        self.verticalLayout_7.addWidget(self.btn_plot)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.btn_makeVideo = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_makeVideo.setEnabled(False)
        self.btn_makeVideo.setObjectName("btn_makeVideo")
        self.verticalLayout_7.addWidget(self.btn_makeVideo)
        self.gridLayout.addWidget(self.groupBox_5, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        # QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Fetching options"))
        self.check_optimize.setText(_translate("MainWindow", "Optimize"))
        self.spin_timeOptimize.setSuffix(_translate("MainWindow", " min"))
        self.groupBox.setTitle(_translate("MainWindow", "Datetime"))
        self.label_2.setText(_translate("MainWindow", "Init"))
        self.label.setText(_translate("MainWindow", "End"))
        self.groupBox_3.setTitle(_translate("MainWindow", "PVs"))
        self.check_allPvs.setText(_translate("MainWindow", "All HLS sensors"))
        self.check_opositeHLS.setText(_translate("MainWindow", "Oposite HLS"))
        self.check_rfPv.setText(_translate("MainWindow", "RF"))
        self.check_earthtides.setText(_translate("MainWindow", "Teorical earth tides"))
        self.check_wellpressure.setText(_translate("MainWindow", "Artesian Well\'s pressure"))
        self.check_selectPvs.setText(_translate("MainWindow", "Selected"))
        self.inputTxt_pvs.setText(_translate("MainWindow", "TU-11C:SS-HLS-Ax48NW5:Level-Mon"))
        self.inputTxt_pvs.setPlaceholderText(_translate("MainWindow", "PVs divided by ;"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Data retrieving"))
        self.label_dataLoaded.setText(_translate("MainWindow", "No data loaded"))
        self.btn_fetchFromArchiver.setText(_translate("MainWindow", "Fetch from Archiver"))
        self.btn_cleanData.setText(_translate("MainWindow", "Clean loaded data"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Analysis"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Options"))
        self.check_plotTime.setText(_translate("MainWindow", "timeseries"))
        self.check_plotFFT.setText(_translate("MainWindow", "FFT"))
        self.check_plotCorrel.setText(_translate("MainWindow", "Correlation"))
        self.check_plotDirectional.setText(_translate("MainWindow", "Directional"))
        self.check_plotStatic.setText(_translate("MainWindow", "Static"))
        self.check_plotDynamic.setText(_translate("MainWindow", "Dynamic"))
        self.check_plot2D.setText(_translate("MainWindow", "2D"))
        self.check_plot3D.setText(_translate("MainWindow", "3D"))
        self.check_applyFilter.setText(_translate("MainWindow", "Apply filter"))
        self.label_4.setText(_translate("MainWindow", "Max period"))
        self.spin_filter_max.setSuffix(_translate("MainWindow", "h"))
        self.label_5.setText(_translate("MainWindow", "Min period"))
        self.spin_filter_min.setSuffix(_translate("MainWindow", "h"))
        self.check_plotFiltSignal.setText(_translate("MainWindow", "plot filtered signal (FFT)"))
        self.check_saveFig.setText(_translate("MainWindow", "save figures"))
        self.inputTxt_dirFig.setPlaceholderText(_translate("MainWindow", "directory name"))
        self.label_3.setText(_translate("MainWindow", "time chunks"))
        self.spin_chunck_day.setSuffix(_translate("MainWindow", " d"))
        self.spin_chunck_hour.setSuffix(_translate("MainWindow", " h"))
        self.spin_chunck_min.setSuffix(_translate("MainWindow", " m"))
        self.btn_plot.setText(_translate("MainWindow", "Plot"))
        self.btn_makeVideo.setText(_translate("MainWindow", "Make video"))
